//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ubigeo
    {
        public int id_Ubigeo { get; set; }
        public string CODDPTO { get; set; }
        public string CODPROV { get; set; }
        public string CODDIS { get; set; }
        public string NOMBRE { get; set; }
        public string COD_DEPT { get; set; }
    }
}
