//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Actividades
    {
        public int id_actividad { get; set; }
        public Nullable<int> id_Ciclo { get; set; }
        public Nullable<System.DateTime> fecha_actividad { get; set; }
        public Nullable<int> id_Duracion { get; set; }
        public string detalle_actividad { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> usuario_aprobador_actividad { get; set; }
        public Nullable<System.DateTime> fecha_respuesta_actividad { get; set; }
        public string mensaje_respuesta_actividad { get; set; }
        public string tipo_interfaz_actividad { get; set; }
        public Nullable<int> id_Medico { get; set; }
    }
}
