//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sol_Medico_Det
    {
        public int id_Sol_Medico_Det { get; set; }
        public Nullable<int> id_Sol_Medico_Cab { get; set; }
        public Nullable<int> id_Medico { get; set; }
        public string mensaje_respuesta_sol_medico_det { get; set; }
        public Nullable<System.DateTime> fecha_respuesta_sol_medico_det { get; set; }
        public Nullable<int> usuario_respuesta_sol_medico_det { get; set; }
        public Nullable<int> estado_sol_medico_det { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
