//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Medicos
    {
        public int id_Medico { get; set; }
        public int id_Identificador_Medico { get; set; }
        public string cmp_medico { get; set; }
        public string nombres_medico { get; set; }
        public string apellido_paterno_medico { get; set; }
        public string apellido_materno_medico { get; set; }
        public Nullable<int> id_Categoria { get; set; }
        public Nullable<int> id_Especialidad1 { get; set; }
        public Nullable<int> id_Especialidad2 { get; set; }
        public string email_medico { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento_medico { get; set; }
        public string sexo_medico { get; set; }
        public string telefono_medico { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> id_tipo_visita { get; set; }
    }
}
