//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Examen_Rm_Resolucion_Det
    {
        public int id_Examen_Rm_Resolucion_Det { get; set; }
        public Nullable<int> id_Examen_Rm_Resolucion_Cab { get; set; }
        public Nullable<int> id_Examen_RM_Det_Preguntas { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string texto_respuesta { get; set; }
    }
}
