//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Programacion_Cab
    {
        public int id_Programacion_cab { get; set; }
        public Nullable<int> id_Ciclo { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public Nullable<int> id_Medico { get; set; }
        public Nullable<int> id_Medicos_Direccion { get; set; }
        public string numero_visita_programacion_cab { get; set; }
        public Nullable<System.DateTime> fecha_programacion_programacion_cab { get; set; }
        public Nullable<System.DateTime> hora_programacion_programacion_cab { get; set; }
        public Nullable<System.DateTime> fecha_reporte_programacion_cab { get; set; }
        public Nullable<System.DateTime> hora_reporte_programacion_cab { get; set; }
        public Nullable<int> id_resultado_visita { get; set; }
        public string visita_acompaniada_programacion_cab { get; set; }
        public string datos_acompaniante_programacion_cab { get; set; }
        public string latitud_programacion_cab { get; set; }
        public string longitud_programacion_cab { get; set; }
        public Nullable<int> estado_programacion_cab { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string tipo_interfaz_programacion_cab { get; set; }
    }
}
