//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Programacion_Det
    {
        public int id_Programacion_det { get; set; }
        public Nullable<int> id_Programacion_cab { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public string lote_programacion_det { get; set; }
        public Nullable<decimal> cantidad_programacion_det { get; set; }
        public Nullable<int> orden_programacion_det { get; set; }
    }
}
