//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Examen_Rm_Det_Preguntas
    {
        public int id_Examen_RM_Det_Preguntas { get; set; }
        public Nullable<int> id_Examen_Rm_Cab { get; set; }
        public Nullable<int> item_pregunta { get; set; }
        public string descripcion_pregunta { get; set; }
        public Nullable<decimal> puntaje_pregunta { get; set; }
        public Nullable<int> item_alternativa { get; set; }
        public string descripcion_alternativa { get; set; }
        public Nullable<int> es_respuesta { get; set; }
        public Nullable<int> tipo_pregunta { get; set; }
    }
}
