//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Gastos
    {
        public int id_gastos { get; set; }
        public Nullable<System.DateTime> fecha_gastos { get; set; }
        public string ruc { get; set; }
        public string razon_social { get; set; }
        public Nullable<int> id_concepto_gastos { get; set; }
        public string id_tipo_documento { get; set; }
        public string serie_documento { get; set; }
        public string numero_documento { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<double> total { get; set; }
        public string observaciones { get; set; }
        public string imagen { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string tipo_interfaz { get; set; }
    }
}
